### ISSUE TITLE
pycall error - No module named 'pycall

### ISSUE THREAD

**Issue by jrcmoura** [rdegges/pycall#21]
im trying to run these lines of code in PyCharm 2020.2.1 and Python 3.8.3:

call.py

# Initiate an internal call to 100 and say
# 'hello world!' when the caller answers.

from pycall import CallFile, Call, Application

call = Call('SIP/100')
action = Application('Playback', 'hello-world')

c = CallFile(call, action)
c.spool()

i faced with this message error

C:\PythonProgram\pycall-master\tests>python call.py
Traceback (most recent call last):
  File "call.py", line 4, in <module>
    from pycall import CallFile, Call, Applica
ModuleNotFoundError: No module named 'pycall'

Could you help me solving my problem?
thank you in advance

**Comment by jrcmoura** [comment]
Hi rdegges, thanks alot for your answer!
I have done the installation, but show me another message error.

C:\PythonProgram\CallTest>python call.py
Traceback (most recent call last):
  File "call.py", line 1, in <module>
    from pycall import CallFile, Call, Application
  File "C:\11-Programas\anaconda3\lib\site-packages\pycall\__init__.py", line 8, in <module>    from .callfile import CallFile
  File "C:\11-Programas\anaconda3\lib\site-packages\pycall\callfile.py", line 7, in <module>    from pwd import getpwnam
ModuleNotFoundError: No module named 'pwd'
